version: "2.4"
services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    hostname: mongodb
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    # ports:
    #   - 27017:27017

  sample-flask:
    image: "signoz/sample-flask-app:latest"
    container_name: sample-flask
    hostname: sample-flask
    ports:
      - 5002:5002
    extra_hosts:
      - signoz:host-gateway
    environment:
      MONGO_HOST: mongodb
      OTEL_RESOURCE_ATTRIBUTES: service.name=sample-flask
      OTEL_EXPORTER_OTLP_ENDPOINT: http://signoz:4317  # Replace to appropriate SigNoz OtelCollector endpoint, if applicable
